# Generated by Django 3.0.7 on 2020-06-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_searcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
