# Generated by Django 3.0.7 on 2020-06-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_searcher', '0002_remove_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField()),
                ('start_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_searcher.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
