# Generated by Django 3.0.7 on 2020-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_searcher', '0004_auto_20200628_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
