# Generated by Django 3.0.7 on 2020-07-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_searcher', '0005_item_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='trackingdetails',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='trackingdetails',
            name='start_price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_searcher.Item')),
            ],
        ),
    ]
